# Generated by Antigravity [Forge: Gemini 3.0] | Spec: [Architect: Opus 4.5]
"""Research Agent Package - Local Deep Researcher using DeepAgents Framework."""

from research_agent.tools import tavily_search, think_tool
from research_agent.prompts import (
    RESEARCH_WORKFLOW_INSTRUCTIONS,
    RESEARCHER_INSTRUCTIONS,
    SUBAGENT_DELEGATION_INSTRUCTIONS,
    CRITIQUE_PROMPT,
)

__all__ = [
    "tavily_search",
    "think_tool",
    "RESEARCH_WORKFLOW_INSTRUCTIONS",
    "RESEARCHER_INSTRUCTIONS",
    "SUBAGENT_DELEGATION_INSTRUCTIONS",
    "CRITIQUE_PROMPT",
]
